pid /tmp/nginx.pid;

events {
  worker_connections 1024;
}

http {
  server {
    listen 80;
    server_name _;

    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/localhost.pem;
    ssl_certificate_key /etc/nginx/localhost.key;

    root /var/www/nginx;

    error_page 404 /errors/404.html;

    location = /errors/404.html {
      internal;
    }

    location / {
      return 404;
    }
  }
}
